### ISSUE TITLE
Waray

### ISSUE THREAD

**Issue by barlowrussell** [numeralbank/googleuninum#5]
The language given as Waray [wrz] is actually Waray (Philippines) [war]. All the numerals in this list are loans from Spanish.

**Comment by chrzyki** [comment]
I'd suggest raising this issue upstream, i.e. here: https://github.com/google-research-datasets/uninum. If they don't want to/can't fix the issue we'll do it programmatically here.

**Comment by chrzyki** [comment]
Note that this would of course affect all the upstream information, meaning the Ethnologue reference, the Glottolog reference, ISO codes, etc.

**Comment by barlowrussell** [comment]
Ah, thanks. Yes, that makes sense, I'll try to raise the issue there :)
